Solution for #7568: Equivalence of boolean condition in partial index
FirebirdSQL/firebird pull request #7987
Opened 2024-01-30 17:40 UTC by dyemanov

Patch consists of two parts:

1. Transform `NOT A = {FALSE | TRUE}` into `A = {TRUE | FALSE}` (with inverted literal) rather than keeping the condition as is or transforming it into `A <> {FALSE | TRUE}`
2. Detect equivalence of different types of comparisons involving (explicitly or implicitly) boolean literals

Using the same test case as in #7568:

```
create table OFFER (
  OFFER_ID bigint generated always as identity primary key,
  PRODUCT_ID bigint not null,
  ARCHIVED boolean default false not null,
  PRICE decimal(9,2) not null
);

create unique index IDX_OFFER_UNIQUE_PRODUCT 
  on OFFER (PRODUCT_ID)
  where not ARCHIVED;
```

all the following SQL queries are now able to use an index:

```
select * from offer where not archived;

select * from offer where archived = false;
select * from offer where false = archived;

select * from offer where archived is not distinct from false;
select * from offer where false is not distinct from archived;

select * from offer where archived <> true;
select * from offer where true <> archived;

select * from offer where archived is distinct from true;
select * from offer where true is distinct from archived;

select * from offer where not archived = true;
select * from offer where not true = archived;

select * from offer where not archived is not distinct from true;
select * from offer where not true is not distinct from archived;

select * from offer where not archived is distinct from false;
select * from offer where not false is distinct from archived;

select * from offer where archived is false;
select * from offer where archived is not true;

select * from offer where not archived is true;
select * from offer where not archived is not false;
```

2024-01-30 23:49 UTC, asfernandes requested changes

2024-01-30 23:49 UTC, asfernandes commented on src/dsql/ExprNodes.h
> +		return *reinterpret_cast<bool*>(litDesc.dsc_address);
dtype_boolean is encoded in UCHAR, not `bool` (which has unspecified size).

```suggestion
		return *litDesc.dsc_address != '\0';
```

2024-01-31 09:47 UTC, mrotteveel commented
I'm not sure about the correctness for `IS [NOT] DISTINCT FROM`, given `archived is distinct from true` covers both `false` and `null`, and not just `false`.

2024-01-31 09:51 UTC, mrotteveel commented
(in the example it works because `archived` is marked not null, but this isn't generally applicable)

2024-02-01 10:16 UTC, dyemanov commented
Yes, it appears I was over-optimistic in this regard :-(
And AFAIU the same issue applies to `IS [NOT] {FALSE | TRUE}`, as `A = TRUE` and `A IS NOT FALSE` return different results for `A` being `NULL`.

2024-02-01 18:48 UTC, dyemanov commented
At the first glance I thought that `A = false` and `A is not distinct from false` could be considered equivalent, but they also return different values when `A IS NULL` -- `NULL vs FALSE` -- and even if the boolean condition handles them the same way I'm afraid this may strike us back in more complex expressions like `(A = false) is unknown`. So it appears for the safety reasons we should limit our optimization attempts with `=` and `<>` only.

2024-02-02 09:26 UTC, dyemanov commented
I've adjusted the patch and the description of possible replacements.

2024-02-02 10:00 UTC, asfernandes approved these changes

2024-02-02 10:07 UTC, merged

2024-02-03 05:47 UTC, pavel-zotov commented
QA issue: see test for #7568