Attempt to fix #8082 by making engine to use user buffers directly
FirebirdSQL/firebird pull request #8145
Opened 2024-05-30 15:12 UTC by aafemt

Plan "A" is simple:
1) Get rid of EOS variable because user buffers have no room for it.
2) Modify ParameterNode to use actual message metadata and message buffer instead of one generated during compilation and scratch area.

2024-06-28 16:03 UTC, aafemt commented
At this point the testcase for #8082 produces exactly expected output.

2024-07-29 16:10 UTC, aafemt commented
Previous commit should completely resolve #8185 moving linkage to parent cursor from DsqlStatement into DsqlRequest so changes from #8189 were partially undone.

2024-07-30 00:12 UTC, asfernandes commented
> Previous commit should completely resolve #8185 moving linkage to parent cursor from DsqlStatement into DsqlRequest so changes from #8189 were partially undone.

#8185 is already fixed in different ways in master and v5. I see no relation of #8189 with this PR. I actually see no relation of this PR with actual problem of #8082.

In reality, I do not understand what is this PR about.

2024-07-30 09:23 UTC, aafemt commented
What I see in master is just disabled caching for queries with cursor name set (which is 100% in Delphi applications). Reference to #8189 was mistype, I meant #8191. The change in this PR made DsqlStatement constant so it can be cached freely (up to reuse of single instances simultaneously).

2024-07-30 14:19 UTC, aafemt commented
> disabled caching for queries with cursor name set

Sorry, "reference to cursor" meant here. And Delphi applications are not affected more than others. My fault.

2024-08-09 16:20 UTC, aafemt commented
Additionally failed QA tests:

1. tests/bugs/core_4374_test.py failed because BLR generated for `SUSPEND` is three bytes shorter. (Redundant blr_begin, blr_stall, blr_end were removed.)
2. tests/bugs/core_5973_test.py failed because deprecated SQLCODE was removed from error messages in refactored code.
3. tests/bugs/gh_6910_test.py failed because output message is no more generated for Execute Block without output.

2024-11-08 12:03 UTC, aafemt commented
Could someone review this, please?

2024-12-05 13:02 UTC, aafemt commented
I wonder why these Android runners are so unstable.

2025-04-19 17:19 UTC, dyemanov requested changes

2025-04-19 17:19 UTC, dyemanov commented on src/dsql/StmtNodes.cpp
> +	if (buffer->buffer == nullptr)
Better naming, please. `buffer->buffer` reads terribly. I'd suggest something like `MessageBuffer::data` instead.

2025-04-19 17:19 UTC, dyemanov commented on src/dsql/StmtNodes.cpp
> +		size_t length = buffer->format == nullptr ? format->fmt_length : buffer->format->fmt_length;
```suggestion
		const ULONG length = buffer->format == nullptr ? format->fmt_length : buffer->format->fmt_length;
```

2025-04-20 16:28 UTC, aafemt commented on src/dsql/ExprNodes.cpp
> +		{
No, this code is intended for usage with blr_record_version as well as described by the comment below. Currently it cannot be executed for it because compound record streams cannot be updated at all, the check is outside of this code.

2025-04-20 16:28 UTC, aafemt commented on src/jrd/exe.cpp
> +	UCHAR* msgBuffer = messageNode->getBuffer(request);
Some more usage was here during debugging. Optimizer will eliminate it anyway.

2025-04-20 16:28 UTC, aafemt commented on src/dsql/ExprNodes.cpp
> +						node->dsqlVar->msgNumber, static_cast<decltype(dsqlScratch->outerMessagesMap)::ValueType>(2 + dsqlScratch->outerMessagesMap.count()));
As with `auto` keyword it allows freely change the type in a single place without worry about the rest, but ok.

2025-04-20 16:28 UTC, aafemt commented on src/dsql/DsqlRequests.cpp
>  	}
Because throwing in destructor is a very bad idea. Calling code can be unprepared for this. It is emergency case that should never happen so it is better to swallow the exception (in release build only) and let resources be finalized by pool.

2025-04-22 07:42 UTC, dyemanov commented on src/dsql/DsqlStatements.h
>  	//static const unsigned FLAG_BLR_VERSION5	= 0x08;
Please wipe them out.

2025-04-22 07:49 UTC, dyemanov commented on src/dsql/DsqlCursor.cpp
> +		m_keyBuffer = new RecordKey[req->req_rpb.getCount()];
Default pool is usually `tdbb->getDefaultPool()`, although maybe here we could use `req->req_pool` explicitly ?
I dislike unpooled `new` due to lost memory usage statistics which otherwise could be counted and reported.

2025-04-22 08:04 UTC, dyemanov commented on src/dsql/DsqlCursor.cpp
> +			m_keyBuffer = new RecordKey[req->req_rpb.getCount()];
It's a pity. Do you know if `setCursorName()` is really called after `openCursor()` is practice (e.g. by Delphi applications) or is it just a protection from this theoretically happening? Do you think we could delay the `dbkey/recver` message setup until `setCursorName()` is called? At least for unbuffered (unidirectional) fetches?

2025-04-22 08:57 UTC, aafemt commented on src/dsql/DsqlCursor.cpp
> +		m_keyBuffer = new RecordKey[req->req_rpb.getCount()];
Memory accounting is a good reason (though size of the key buffer is hardly noticeable), but ownBuffer below is a local variable with short lifetime, should it be really accounted?

2025-04-22 10:57 UTC, aafemt commented on src/dsql/DsqlCursor.cpp
> +		m_keyBuffer = new RecordKey[req->req_rpb.getCount()];
@AlexPeshkoff Even for local variables of type `std::unique_ptr`? They are guaranteed not to leak.

2025-04-22 11:06 UTC, aafemt commented on src/dsql/DsqlCursor.cpp
> +		m_keyBuffer = new RecordKey[req->req_rpb.getCount()];
BTW, what must be used for arrays? `FB_NEW(pool) char[X]` or `FB_NEW_RPT(pool, X) char`?

2025-04-22 11:29 UTC, AlexPeshkoff commented on src/dsql/DsqlCursor.cpp
> +		m_keyBuffer = new RecordKey[req->req_rpb.getCount()];
> Even for local variables

Better for them too. 

> FB_NEW(pool) char[X] or FB_NEW_RPT(pool, X) char?

There are 3 macro:
FB_NEW - like plain new (use default pool), but adds lineno info.
FB_NEW_POOL(pool) - also use specific pool
FB_NEW_RPT(pool, N) - apllied only for special classes ready for rpt allocation (left not much of them)

So for array use:
FB_NEW_POOL(pool) char[X]

2025-04-29 05:19 UTC, dyemanov commented
Please cleanup `req_user_descs` that's no longer needed. I'm OK with the PR, just willing to do a few tests before merging.

2025-05-06 06:31 UTC, dyemanov approved these changes

2025-05-06 10:52 UTC, AlexPeshkoff approved these changes

2025-05-07 08:28 UTC, merged

2025-05-17 01:13 UTC, asfernandes commented
This PR broke WHERE CURRENT OF maybe mixed with RETURNING.
The tests I have is private, so I cannot easily share it, but probably any usage is going to cause problem.
Error is: `undefined message number`

2025-05-18 12:50 UTC, mrotteveel commented
Given the problems this PR seems to have introduced, shouldn't it be backed out/reverted?

2025-06-26 11:31 UTC, asfernandes commented
This PR also breaks TCS test AUTO_COMMIT.3.ESQL.

2025-06-26 11:35 UTC, asfernandes commented
And it's also not fixed by https://github.com/FirebirdSQL/firebird/pull/8571.

2026-01-01 15:06 UTC, asfernandes commented
> This PR broke WHERE CURRENT OF maybe mixed with RETURNING. The tests I have is private, so I cannot easily share it, but probably any usage is going to cause problem. Error is: `undefined message number`

@aafemt are you waiting for this problem to celebrate anniversary?

2026-01-01 15:08 UTC, aafemt commented
You do have the testcase, not me.

2026-01-01 16:57 UTC, aafemt commented
With or without `RETURNING` I cannot reproduce the issue.

PS: api6.c example that I tried to use as the testcase is been broken for 13 years.